version: '3.8'

services:
  app:
    container_name: ttn
    image: ghcr.io/yunuo46/ttn:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://ttn_db:3306/ttn?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql

  mysql:
    container_name: ttn_db
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ttn
    ports:
      - "3306:3306"
