version: '3.8'

services:
  app:
    image: ghcr.io/yunuo46/ttn:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ttn
    ports:
      - "3306:3306"